travis:
  secure:
    BINSTAR_TOKEN: ZJxqOOmxJmmSZbJ+UoYc9F3ELqkQ6gbmi2QC5e5f+unUZCuMI2+owHb2CBrnChWO0ww5toN/4fPyHghrS8GtHMRONGsGayl578ehvnDvSM5YpNy9eyqHWjlWOvbXRmS4s03bLQ98kwsTvKZu9qk3fUxQ+8s8WZwopisVjm7cHIKeof/I1Ib9nbjcTDUa2+51d7R3ixASYK1lz9w0AAgOsC21X9qLX+zxJq5THIA8mN/TMwktBXEjCTkUXT7BEGKV0L8O5CDGm/rj2Rs45BbVWFIOh/fymML48SgNBu6GKXZswwGD9a/3SpdZx2lNwJq/4pLtaT2oeEUcZd1lOiBlhgzNMsBspcioI6YbfBs7fRRa6hmu9GNX6oxZfCIBSfW/GSICzN0QEXWzXMEeIUtXQUAdqrCOXg+D5ySCjBJ3W+ymrbzugCDFXBdtvUpXE9yNfpDyUXzgkNNL3uGJ3Msdq5pqS/3YEBsX5WKXdim37RqM9FFd8pJrnIGohMlfTY8bfy6KJQi1bNmf1ok0BzKFK4/uIjg/H3we5j1VWHc+5vJyDY7waje6s4cr9LV6UD6kWPKLVD0wqizu9rJ2gbD2Sa0BkBsd0pVrTC9MoZXMnNUF5/dD7rvCBBGk4962WsZOiknL49bSWkAkMybTHavWuBnBQ6L3rH+DCkgJVTknZ4A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
